# CHANGELOG
#
# 1.0.0  03-APR-2023  Initial version
#
---
aircraft: Toliss A321neo
description: Definition of decks for Toliss A321 + neo add-on
icao: A21N
model: Airbus A321-253N (CFM LEAP-1A33)
# ########################
decks:
  - name: XPLive
    type: loupedeck
    layout: fcu
    brightness: 80
    light-off: 5
  - name: XPDeck
    type: streamdeck
    layout: efis-ecam
    brightness: 80
    light-off: 5
  - name: XPDeckXL
    layout: consoles
    type: streamdeck
    brightness: 80
  - name: XPTouch
    type: xtouchmini
    layout: comm-radio
    brightness: 80
    # disabled: true
# This is at aircraft-level level
default-wallpaper-logo: logo.png
default-icon-color: (94, 111, 130)
default-label-font: DIN Medium.ttf
default-label-size: 13
default-label-color: white
empty-key-fill-color: (94, 111, 130)
