# CHANGELOG
#
# 1.0.0  03-APR-2023  Initial version
#
---
aircraft: Toliss A321neo
description: Definition of decks for Toliss A321 + neo add-on
icao: A21N
model: Airbus A321-253NY (CFM LEAP-1A33)
notes: A321 XLR, MSN 11000, F-WXLR, ICAO24=395CBB
# NY = A321 XLR
# ########################
decks:
  - name: XPLive
    type: loupedeck
    layout: fcu
    brightness: 80
    light-off: 5
  - name: XPDeck
    type: streamdeck
    layout: efis-ecam
    brightness: 100
    light-off: 5
  - name: XPDeckXL
    layout: consoles
    type: streamdeck
    brightness: 100
  - name: XPTouch
    type: xtouchmini
    layout: comm-radio
    brightness: 80
    # disabled: true
# This is at aircraft-level level
default-icon-color: (94, 111, 130)
default-label-font: B612-Bold
default-label-size: 12
default-label-color: white
# debug: cockpitdecks.cockpit
cockpit-texture: TEXTURE.png
annunciator-style: v
