actions:
  - index: 0
    name: X-Plane Map
    type: single
    icon: dual.0.0
    command: sim/map/show_current
  - index: 1
    name: X-Plane Map1
    type: single
    icon: dual.0.0
    command: sim/map/show_current
  - index: 2
    type: nonexistanttype
    icon: dual.0.0
    command: sim/map/show_current
  - name: No Index
    type: single
    icon: dual.0.0
    command: sim/map/show_current
  - index: 33
    name: X-Plane Map
    type: single
    icon: dual.0.0
    command: sim/map/show_current
