# ##############################
#
# MAIN SYSTEM CONFIGURATION FILE
#
# 1. NETWORK SETTING
#
# Where X-Plane runs
#
XP_HOST: "mac-mini-de-pierre.local"
# X-Plane not on this host
XP_HOME:

API_HOST:
# if None, set to self.beacon_data['IP']
API_PORT: 8080
API_PATH: /api/v1

#
# Where Cockpitdecks runs
#
APP_HOST: [mac-studio-de-pierre.local, 7777]
