# ##############################
#
# MAIN SYSTEM CONFIGURATION FILE
#
# 1. NETWORK SETTING
#
# Where X-Plane runs
#
XP_HOST: mac-studio-de-pierre.local
# X-Plane not on this host
XP_HOME: /Users/pierre/X-Plane 12

API_HOST: 127.0.0.1
# if None, set to self.beacon_data['IP']
API_PORT: 8086
API_PATH: /api/v1

#
# Where Cockpitdecks runs
#
APP_HOST: [mac-studio-de-pierre.local, 7777]
