[project]
name = "cockpitdecks"
version = "1.0.0"

authors = [
  { name="Pierre M.", email="pierre@devleaks.be" },
]

description = "Decks and web decks to X-Plane Cockpit"

readme = "README.md"

requires-python = ">=3.10"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
   "CairoSVG>=2.7.1",
   "Flask>=3.0.3",
   "pillow>=10.4.0",
   "psutil>=6.0.0",
   "ruamel.yaml>=0.18.6",
   "simple-websocket>=1.0.0"
]

license = {text = "MIT License"}

[project.urls]
Homepage = "https://github.com/devleaks/cockpitdecks"
Issues = "https://github.com/devleaks/cockpitdecks/issues"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 160
docstring-code-format = true
select = [
    "E",
    "F",
    "W",
]
ignore = []

[tool.black]
line-length = 160
