# Definition of decks for Toliss A321
#
aircraft: Toliss A321
decks:
  - name: XPLive
    type: loupedeck
    layout: live
    brightness: 80
    light-off: 5
  - name: XPDeck
    type: streamdeck
    layout: sd15
    brightness: 80
    light-off: 5
    default-label-font: DIN Medium.ttf
    default-label-size: 13
  - name: XPDeckXL
    layout: overhead
    type: streamdeck
    brightness: 80
    default-label-font: DIN Bold.ttf
    default-label-size: 16
  - name: XPTouch
    type: xtouchmini
    layout: xtouchold
    brightness: 80
    # disabled: True
    # We use X-Touch from X-Keypad for better control
# This is at global level
default-wallpaper-logo: logo.png
default-icon-color: (94, 111, 130)
default-label-color: white
default-label-font: DIN.ttf
default-label-size: 14
empty-key-fill-color: (94, 111, 130)