# CHANGELOG
#
# 1.0.0  03-APR-2023  Initial version
#
---
aircraft: Toliss A321neo
description: Configuration parameters for Streamdeck 32 keys
version: 1.0.0
# ########################
# This config is at deck level
empty-key-fill-color: (94, 111, 130)
default-label-size: 12
default-label-font: DIN Medium.ttf
annunciator-style: k
# homepage-name: xplane
