aicraft: Toliss A321
decks:
  - name: XPDeck
    serial: DL16L1A81614
    layout: layout15
    brightness: 30
    default-label-font: DIN Medium.ttf
    default-label-size: 13
  - name: XPDeckXL
    serial: CL16L2A09596
    layout: layout32
    brightness: 70
    default-label-font: DIN Bold.ttf
    default-label-size: 16
# This is at global level
default-wallpaper-logo: logo.png
default-label-color: white
default-label-font: DIN.ttf
default-label-size: 14
