# This is at Cockpitdeck level, for all aircrafts
#
# This file should not contain any customization of appearance like color, image, icon, etc.
# since it should be usable by all aircrafts.
---
# ##################################################
# Application values
#
cache-icon: True
default-icon-name: none.png
# debug: cockpitdecks.deck
#
# ##################################################
# Default color and themes
#
# cockpit-theme: dark
#
# cockpit-theme: dark
# Color (16, 16, 32) is close to
# average texture color TEXTURE_NIGHT.
#
# dark-cockpit-color: [16, 16, 32]
# dark-default-icon-color: [16, 16, 32]
# dark-default-annunciator-style: k
# dark-default-label-color: coral
# dark-default-light-off-intensity: 4
# dark-default-text-color: coral
# dark-default-text-position: cm
# dark-default-tick-color: coral
# dark-default-tick-label-color: coral
# dark-default-tick-underline-color: coral
#
# ##################################################
# Rendez-vous variables to trigger events in Cockpit
#
permenant-variable-names:
  - aircraft-name
  - aircraft-icao
  - livery-name
  - livery-index
#
# ##################################################
# Dataref roundings and reading frequencies (if non standard)
#
dataref-fetch-frequencies:
  sim/flightmodel/position/latitude: 1
  sim/flightmodel/position/longitude: 1
dataref-roundings:
  # Negative rounding value
  #
  # IMPORTANT: Rounding is done in Python.
  # Negative rounding can be used to round to power of ten:
  # round(123456.789, -4) = 120000
  #
  sim/time/zulu_time_sec: 0
  sim/cockpit/autopilot/heading_mag: 2
  sim/cockpit2/gauges/actuators/barometer_setting_in_hg_pilot: 4
  sim/weather/barometer_current_inhg: 4
  # used in Weather button 3 or 4 decimals sufficient...
  sim/flightmodel/position/latitude: 8
  sim/flightmodel/position/longitude: 8
  sim/cockpit/misc/barometer_setting: 2
  AirbusFBW/BatVolts[0]: 1
  AirbusFBW/BatVolts[1]: 1
  AirbusFBW/OHPLightsATA34[6]: 3
  AirbusFBW/OHPLightsATA34[8]: 3
  AirbusFBW/OHPLightsATA34[10]: 3
  AirbusFBW/OHPLightsATA30[0]: 3
  AirbusFBW/OHPLightsATA30[1]: 3
  AirbusFBW/OHPLightsATA30[2]: 3
  AirbusFBW/OHPLightsATA30[3]: 3
  AirbusFBW/OHPLightsATA30[4]: 3
  AirbusFBW/OHPLightsATA30[5]: 3
  AirbusFBW/OHPLightsATA30[10]: 3
  AirbusFBW/OHPLightsATA30[11]: 3
  AirbusFBW/OHPLightsATA21[13]: 3
  AirbusFBW/OHPLightsATA31[*]: 3
  sim/flightmodel/weight/m_fuel_total: 0
  # This is for Region Real Weather,
  # it does not need to be updated frequently...
  sim/weather/region/atmosphere_alt_levels_m[*]: 1
  sim/weather/region/change_mode: 1
  sim/weather/region/cloud_base_msl_m[*]: 1
  sim/weather/region/cloud_coverage_percent[*]: 1
  sim/weather/region/cloud_tops_msl_m[*]: 1
  sim/weather/region/cloud_type[*]: 1
  sim/weather/region/dewpoint_deg_c[*]: 1
  sim/weather/region/qnh_base_elevation: 1
  sim/weather/region/rain_percent: 1
  sim/weather/region/runway_friction: 1
  sim/weather/region/sealevel_pressure_pas: 1
  sim/weather/region/sealevel_temperature_c: 1
  sim/weather/region/shear_direction_degt[*]: 1
  sim/weather/region/shear_speed_msc[*]: 1
  sim/weather/region/temperature_altitude_msl_m[*]: 1
  sim/weather/region/temperatures_aloft_deg_c[*]: 1
  sim/weather/region/thermal_rate_ms: 1
  sim/weather/region/turbulence[*]: 1
  sim/weather/region/update_immediately: 1
  sim/weather/region/variability_pct: 1
  sim/weather/region/visibility_reported_sm: 1
  sim/weather/region/wave_amplitude: 1
  sim/weather/region/wave_dir: 1
  sim/weather/region/wave_length: 1
  sim/weather/region/wave_speed: 1
  sim/weather/region/weather_source: 1
  sim/weather/region/wind_altitude_msl_m[*]: 1
  sim/weather/region/wind_direction_degt[*]: 1
  sim/weather/region/wind_speed_msc[*]: 1
  sim/weather/aircraft/altimeter_temperature_error: 1
  sim/weather/aircraft/barometer_current_pas: 1
  sim/weather/aircraft/cloud_base_msl_m[*]: 1
  sim/weather/aircraft/cloud_coverage_percent[*]: 1
  sim/weather/aircraft/cloud_tops_msl_m[*]: 1
  sim/weather/aircraft/cloud_type[*]: 1
  sim/weather/aircraft/dewpoint_deg_c[*]: 1
  sim/weather/aircraft/gravity_mss: 1
  sim/weather/aircraft/precipitation_on_aircraft_ratio: 1
  sim/weather/aircraft/qnh_pas: 1
  sim/weather/aircraft/relative_humidity_sealevel_percent: 1
  sim/weather/aircraft/shear_direction_degt[*]: 1
  sim/weather/aircraft/shear_speed_kts[*]: 1
  sim/weather/aircraft/speed_sound_ms: 1
  sim/weather/aircraft/temperature_ambient_deg_c: 1
  sim/weather/aircraft/temperature_leadingedge_deg_c: 1
  sim/weather/aircraft/temperatures_aloft_deg_c[*]: 1
  sim/weather/aircraft/thermal_rate_ms: 1
  sim/weather/aircraft/turbulence[*]: 1
  sim/weather/aircraft/visibility_reported_sm: 1
  sim/weather/aircraft/wave_amplitude: 1
  sim/weather/aircraft/wave_dir: 1
  sim/weather/aircraft/wave_length: 1
  sim/weather/aircraft/wave_speed: 1
  sim/weather/aircraft/wind_altitude_msl_m[*]: 1
  sim/weather/aircraft/wind_direction_degt[*]: 1
  sim/weather/aircraft/wind_now_x_msc: 1
  sim/weather/aircraft/wind_now_y_msc: 1
  sim/weather/aircraft/wind_now_z_msc: 1
  sim/weather/aircraft/wind_speed_kts[*]: 1
  sim/weather/aircraft/wind_speed_msc: 1
