# This is at Cockpitdeck level, for all aircrafts
#
# This file should not contain any customization of appearance like color, image, icon, etc.
# since it should be usable by all aircrafts.
---
cache-icon: True
default-icon-name: none.png
dataref-roundings:
  sim/cockpit/autopilot/heading_mag: 2
  # used in Weather button 3 or 4 decimals sufficient...
  sim/flightmodel/position/latitude: 8
  sim/flightmodel/position/longitude: 8
  sim/cockpit/misc/barometer_setting: 2
  AirbusFBW/BatVolts[0]: 1
  AirbusFBW/BatVolts[1]: 1
  AirbusFBW/OHPLightsATA34[6]: 3
  AirbusFBW/OHPLightsATA34[8]: 3
  AirbusFBW/OHPLightsATA34[10]: 3
  AirbusFBW/OHPLightsATA30[0]: 3
  AirbusFBW/OHPLightsATA30[1]: 3
  AirbusFBW/OHPLightsATA30[2]: 3
  AirbusFBW/OHPLightsATA30[3]: 3
  AirbusFBW/OHPLightsATA30[4]: 3
  AirbusFBW/OHPLightsATA30[5]: 3
  AirbusFBW/OHPLightsATA30[10]: 3
  AirbusFBW/OHPLightsATA30[11]: 3
  # cabin pressure ditching
  AirbusFBW/OHPLightsATA21[13]: 3
  sim/flightmodel/weight/m_fuel_total: 0
  # This is for Region Real Weather,
  # it does not need to be updated frequently...
  sim/weather/region/atmosphere_alt_levels_m[*]: 1
  sim/weather/region/change_mode: 1
  sim/weather/region/cloud_base_msl_m[*]: 1
  sim/weather/region/cloud_coverage_percent[*]: 1
  sim/weather/region/cloud_tops_msl_m[*]: 1
  sim/weather/region/cloud_type[*]: 1
  sim/weather/region/dewpoint_deg_c[*]: 1
  sim/weather/region/qnh_base_elevation: 1
  sim/weather/region/rain_percent: 1
  sim/weather/region/runway_friction: 1
  sim/weather/region/sealevel_pressure_pas: 1
  sim/weather/region/sealevel_temperature_c: 1
  sim/weather/region/shear_direction_degt[*]: 1
  sim/weather/region/shear_speed_msc[*]: 1
  sim/weather/region/temperature_altitude_msl_m[*]: 1
  sim/weather/region/temperatures_aloft_deg_c[*]: 1
  sim/weather/region/thermal_rate_ms: 1
  sim/weather/region/turbulence[*]: 1
  sim/weather/region/update_immediately: 1
  sim/weather/region/variability_pct: 1
  sim/weather/region/visibility_reported_sm: 1
  sim/weather/region/wave_amplitude: 1
  sim/weather/region/wave_dir: 1
  sim/weather/region/wave_length: 1
  sim/weather/region/wave_speed: 1
  sim/weather/region/weather_source: 1
  sim/weather/region/wind_altitude_msl_m[*]: 1
  sim/weather/region/wind_direction_degt[*]: 1
  sim/weather/region/wind_speed_msc[*]: 1
  sim/weather/aircraft/altimeter_temperature_error: 1
  sim/weather/aircraft/barometer_current_pas: 1
  sim/weather/aircraft/cloud_base_msl_m[*]: 1
  sim/weather/aircraft/cloud_coverage_percent[*]: 1
  sim/weather/aircraft/cloud_tops_msl_m[*]: 1
  sim/weather/aircraft/cloud_type[*]: 1
  sim/weather/aircraft/dewpoint_deg_c[*]: 1
  sim/weather/aircraft/gravity_mss: 1
  sim/weather/aircraft/precipitation_on_aircraft_ratio: 1
  sim/weather/aircraft/qnh_pas: 1
  sim/weather/aircraft/relative_humidity_sealevel_percent: 1
  sim/weather/aircraft/shear_direction_degt[*]: 1
  sim/weather/aircraft/shear_speed_kts[*]: 1
  sim/weather/aircraft/speed_sound_ms: 1
  sim/weather/aircraft/temperature_ambient_deg_c: 1
  sim/weather/aircraft/temperature_leadingedge_deg_c: 1
  sim/weather/aircraft/temperatures_aloft_deg_c[*]: 1
  sim/weather/aircraft/thermal_rate_ms: 1
  sim/weather/aircraft/turbulence[*]: 1
  sim/weather/aircraft/visibility_reported_sm: 1
  sim/weather/aircraft/wave_amplitude: 1
  sim/weather/aircraft/wave_dir: 1
  sim/weather/aircraft/wave_length: 1
  sim/weather/aircraft/wave_speed: 1
  sim/weather/aircraft/wind_altitude_msl_m[*]: 1
  sim/weather/aircraft/wind_direction_degt[*]: 1
  sim/weather/aircraft/wind_now_x_msc: 1
  sim/weather/aircraft/wind_now_y_msc: 1
  sim/weather/aircraft/wind_now_z_msc: 1
  sim/weather/aircraft/wind_speed_kts[*]: 1
  sim/weather/aircraft/wind_speed_msc: 1
dataref-fetch-frequencies:
  sim/flightmodel/position/latitude: 1
  sim/flightmodel/position/longitude: 1
  # debug: cockpitdecks.deck
