# Definition of decks for Toliss A321
#
aicraft: Toliss A321
decks:
  - name: XPDeck
    type: streamdeck
    layout: layout15
    brightness: 80
    default-label-font: DIN Medium.ttf
    default-label-size: 13
  - name: XPDeckXL
    layout: pma32
    type: streamdeck
    brightness: 70
    default-label-font: DIN Bold.ttf
    default-label-size: 16
  - name: XPLive
    type: loupedeck
    layout: live
    brightness: 70
  - name: XPTouch
    type: xtouchmini
    layout: touch
    brightness: 70
    disabled: True
# This is at global level
default-wallpaper-logo: logo.png
default-icon-color: (94, 111, 130)
default-label-color: white
default-label-font: DIN.ttf
default-label-size: 14
