# Definition of decks for Toliss A321
#
aicraft: Toliss A321
decks:
  - name: XPDeck
    type: streamdeck
    layout: newdefs
    brightness: 80
    default-label-font: DIN Medium.ttf
    default-label-size: 13
  - name: XPDeckXL
    layout: newdefs
    type: streamdeck
    brightness: 70
    default-label-font: DIN Bold.ttf
    default-label-size: 16
  - name: XPLive
    type: loupedeck
    layout: newdefs
    brightness: 70
  - name: XPTouch
    type: xtouchmini
    layout: newdefs2
    default-homepage-name: A
    brightness: 70
# This is at global level
default-wallpaper-logo: logo.png
default-icon-color: (94, 111, 130)
default-label-color: white
default-label-font: DIN.ttf
default-label-size: 14
